name: places
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  dart_code_metrics: ^4.21.3
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - res/
    - res/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset:  res/fonts/Roboto/Roboto-Black.ttf
        - asset:  res/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset:  res/fonts/Roboto/Roboto-Bold.ttf
        - asset:  res/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset:  res/fonts/Roboto/Roboto-Italic.ttf
        - asset:  res/fonts/Roboto/Roboto-Light.ttf
        - asset:  res/fonts/Roboto/Roboto-LightItalic.ttf
        - asset:  res/fonts/Roboto/Roboto-Medium.ttf
        - asset:  res/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset:  res/fonts/Roboto/Roboto-Regular.ttf
        - asset:  res/fonts/Roboto/Roboto-Thin.ttf
        - asset:  res/fonts/Roboto/Roboto-ThinItalic.ttf
